### PR TITLE
Adjust init methods

### PR DESCRIPTION
**Pull request by robertmryan**
Adjusted init methods to follow standard naming conventions (and facilitate Swift interoperability), specifically
- Deprecated `-(id)init:(NSString *)userAgent`
- Added `-(id)initWithUserAgent:(NSString *)userAgent`

While I was here, I also fixed the cache policy for the request

### CODE REVIEW

**Comment by Stunner** [comment]
I would suggest changing the return type from `id` to `instancetype` while you're at it.

**Comment by robertmryan** [comment]
@Stunner Agreed, that would be appropriate. I contemplated `instancetype` but very consciously decided to make the most minimal edit possible. Also, I looked at the code and saw tons of really dated patterns (all those private ivars included in public interface; using ivars at all rather than properties; using `updatePlay` and `updateGain` methods rather than more conventional setters; etc.), so I hesitated to introduce a single modern Objective C construct, without tackling the more egregious issues.

**Comment by hamedh** [comment]
@robertmryan correct, this was originally written in 2008 so there's a lot of old patterns that haven't been updated but that should be improved

**Comment by robertmryan** [comment]
No worries. It's good of you to share this code with us, despite its age. I just [helped someone out on StackOverflow](http://stackoverflow.com/a/27203184/1271826) who was trying to use these classes and I thought I'd share this minor edit with you. I suspect a more thorough update would be appreciated by those who really want to use these classes, but I also realize that this probably isn't at the top of your list. lol.

**Comment by Stunner** [comment]
:thumbsup:

**Pull request merged**
